### ISSUE TITLE
SlickGrid.setColumns returns type casting error.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#16]
While attempting to pass a List of Columns by either calling SlickGrid.setColumns(myList), or SlilckGrid.setOptions(options) I get this error:
type 'int' is not a subtype of type 'bool' of 'boolean expression'.

The reason why I'm trying to call "setColumns" is that I want to implement a show/hide column feature. Reading the original slickgrid docs pointed me to this function.

**Comment by tonosama-atlacatl** [comment]
Any reason why this is not a bug?

**Comment by cjkao** [comment]
not fully fixed yet, plan to give it default value in next release

**Comment by tonosama-atlacatl** [comment]
ah, ok, I'm sorry if I jumped the gun ;)
AWESOME work BTW.

**Comment by cjkao** [comment]
can't reproduce it using gdoc-header.dart

**Comment by tonosama-atlacatl** [comment]
I was able to reproduce it from your simple.dart example.
I made the column list an external parameter, and under main(), right after g.init(), I called:
g.setColumns(column);
I've tried doing a g.invalidate(), g.render(), and a combo of both. Still, in every case I get this:
slick_grid.dart > line 1767:
Breaking on exception: type 'int' is not a subtype of type 'bool' of 'boolean expression'.
I also tried setting all, minWidth, width, and maxWidth with ints and no luck.

**Comment by cjkao** [comment]
I revised simple.dart, but no luck to made it exception...lol
are you using  0.1.0+9?

**Comment by tonosama-atlacatl** [comment]
Just started, and I'm now looking @ your gdoc-header.dart example.
When I reported this issue, I was on 0.1.07+

**Comment by tonosama-atlacatl** [comment]
Is there a way to simply pass the column List without the new headers. I noticed that the column header click sorts, but the sorting arrows do not match the Sorting Order.

**Comment by tonosama-atlacatl** [comment]
YEEEEEY!!! setColumns work on 0.1.09+ Thank you!!!
no more exception.

**Comment by tonosama-atlacatl** [comment]
This issue is fixed, with one small caveat.
please see:
https://github.com/cjkao/slickdart/issues/17
