### ISSUE TITLE
calling setColumns deselects all checkboxes

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#17]
I'm not sure if we can call this an issue, but would there be a way to retain the checkbox selection upon hiding/showing columns? I see where this eventually gets called: 
I'm using 0.1.0+9
slick_grid.dart:
```dart
setColumns(List<Column> columnDefinitions){
    ...
    if (initialized) {
--->  invalidateAllRows(); <----
        createColumnHeaders();
        removeCssRules();
        createCssRules();
        resizeCanvas();
        applyColumnWidths();
        handleScroll();
      }
    }
```
slick_grid.dart:
```dart
void invalidateAllRows() {
      if (currentEditor!=null) {
        makeActiveCellNormal();
      }
//      rowsCache.clear();
      List tmp=rowsCache.keys.toList(growable: false);
      tmp.forEach((item) => removeRowFromCache(item)) ;
      if (this.selectionModel!=null && this.selectedRows.length>0) {
        this.setSelectedRows([]); <--- Maybe condition this...
      }
    }
```
Honestly, I think you've done a terrific job with this port. Are you open to other's committing into this project as well?

**Comment by tonosama-atlacatl** [comment]
I managed to reset the selection by capturing them before calling .setColumns. It'll be nice if 'setColumns' gave me a choice to retain or wipe them.
```Dart
//Local List of all selections, where _rsm = new RowSelectionModel(...)
_selectedRows = _rsm.getSelectedRows();
//where _sg = SlickGrid pointer
_sg.setColumns(visibleColumns);
_sg.setSelectedRows(_selectedRows);
```

**Comment by cjkao** [comment]
you are right.... remove selected columns is not necessary

**Comment by cjkao** [comment]
feel free to [fork](https://help.github.com/articles/fork-a-repo/) repository and send a [pull request](https://help.github.com/articles/using-pull-requests)

**Comment by tonosama-atlacatl** [comment]
Not an issue as of 0.1.1
