### ISSUE TITLE
was forceFitColumns meant to force columns to take up the full grid's width?

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#24]
This might not be an issue, I'm wondering if this grid option was meant for the following:
Let's say I have a 600px wide grid, and I pass 3 columns. None of the columns contains any width information. If I set the grid option "forceFitColumns" to true, should I expect all 3 columns to take up the 600px, so each column will be ~200px wide? if this is the correct assumption, I cannot seem to get this to work.
If this is not the correct assumption, is there a way to force all columns to take up the remaining space?

Worst comes to worst, I can do some math, but I was wondering if the grid contains some option to make this happen.

Thank you.

**Comment by cjkao** [comment]
I have same thought as you initially , and after some experiment, forceFitColumn only lock the maximum width specified in column options,And it also affect resize column behavior, I need check slickgrid to see  ‎our implementation is right and then add new grid option to fill grid view                                                                                                                                                                                                                                                                                                                                        從我的 BlackBerry 10 智慧型手機傳送。                                                                                                                                                                                                                寄件者： tonosama-atlacatl已傳送： 2015年3月4日星期三 10:09收件者： cjkao/slickdart回覆至： cjkao/slickdart主旨： [slickdart] was forceFitColumns meant to force columns to take up the full grid's width? (#24)This might not be an issue, I'm wondering if this grid option was meant for the following:
Let's say I have a 600px wide grid, and I pass 3 columns. None of the columns contains any width information. If I set the grid option "forceFitColumns" to true, should I expect all 3 columns to take up the 600px, so each column will be ~200px wide? if this is the correct assumption, I cannot seem to get this to work.
If this is not the correct assumption, is there a way to force all columns to take up the remaining space?

Worst comes to worst, I can do some math, but I was wondering if the grid contains some option to make this happen.

Thank you.

—Reply to this email directly or view it on GitHub.

**Comment by tonosama-atlacatl** [comment]
Yeah, I've read online how some people just do crazy math to force/set the column's width. The problem is...If you hide/show columns or resize the grid, you'll have to do this crazy math all over. By crazy math I mean looping thru the column's content to figure out the longest string.length, then doing the same for all columns.... I can see this slowing down the grid if you had something like URLs, or a mixture of short/long string x multiple columns.

**Comment by cjkao** [comment]
fixed in 0.1.1+1
