### ISSUE TITLE
forceFitColumns = true >> throws exceptions if canvas is resized.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#25]
My setup:
A grid with 100% width, 640px height. About 10 columns with no width, min/max width. The grid options contain "forceFitColumns = true". When I resize the browser window to the point where the grid is smaller than all columns I get this error:

type 'int' is not a subtype of type 'bool' of 'boolean expression'.

STACKTRACE:
#0      SlickGrid.autosizeColumns (package:slickdart/slick_grid.dart:578:34)
#1      resizeCanvas (package:slickdart/slick_grid.dart:735:25)
#2      _rootRunUnary (dart:async/zone.dart:906)
#3      _ZoneDelegate.runUnary (dart:async/zone.dart:508)
#4      _onRunUnary.<anonymous closure> (package:angular/core/zone.dart:122:63)
#5      VmTurnZone._onRunBase (package:angular/core/zone.dart:104:16)
#6      _onRunUnary (package:angular/core/zone.dart:122:17)
#7      _CustomZone.runUnary (dart:async/zone.dart:804)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:738)

I'm using: Dart Editor version 1.9.0.dev_09_01 (DEV)

**Comment by cjkao** [comment]
fixed in 0.1.1+1

**Comment by tonosama-atlacatl** [comment]
AWESOME!! thank you!
