### ISSUE TITLE
CheckboxSelectColumn and Column sorting don't keep up with row selection.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#27]
Correct me if this is a "misinterpretation" on my part. I'm using the checkbox column, and 'selecActiveRow' : true , but even if this is false when I select any rows, and then resort any columns. The selection seems to keep the same "row index" selected, but not the same "rows". So if I check say... rows #1, 2, then resort based on some column, rows #1 and 2 should be somewhere else, selected, but that's not what I'm seeing. In this case the first and second checkbox remain selected, with different row's values. Is this a bug or did I overlooked something? 

By the way, the CheckBox.html example behaves this way as well.

I'm on: 
Dart Editor version 1.9.0.dev_09_01 (DEV)
Dart SDK version 1.9.0-dev.9.1

**Comment by cjkao** [comment]
I have revised sort function in  CheckBox.dart. it now correctly set selected items after sorting.
checkbox is a virtual column that does not link with source data, so, we have to maintain selected elements and infer new index after sorting.
Please refer sorting function in CheckBox.dart.
