### ISSUE TITLE
multiSelect = false not respected by the checkbox column header, nor an additional [shift]/[ctrl] + click.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#30]
If my grid uses:
RowSelectionModel({'selectActiveRow':true});
and the checkbox column with grid.options.multiSelect = false;

I see how clicking on any row while holding [ctrl] or [shift] prevents me from selecting that row's checkbox. But, if I actually hold either [ctrl] or [shift] and then click on that row's check box, I'm able to select the row. Also, clicking on the header checkbox allows me to select all rows, which is the opposite from multiSelect  = false.

I can look into fixing this, but I need some guidance as to where to look. I don't even see "multiSelect" being reference anywhere on "slick_column.dart". Should I be looking elsewhere?

Thank you.

**Comment by cjkao** [comment]
the mouse event propagation from grid.click handler -> selection model -> column 
selection column may cancel event for meta/ctrl/shift keyboard combination  to handle select multiple row directly. 
So i made some modification , plz refer to 0.1.1+2

**Comment by tonosama-atlacatl** [comment]
Thank you cjkao!!!
That fixed it, awesome!
