### ISSUE TITLE
Row-click-select the last row causes exception while using FilteredList

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#31]
While using:
RowSelectionModel({'selectActiveRow': true});
and:
FilteredData as the DataProvider.

Let's say the grid has 20 rows. If I click on row 19, I get it's index as "18", which is fine since this is a zero based list. But, every time I click on the last row, It seems as the index jumps one. So in this case, if I click on row 20, I expect to see index 19, but instead I get this exception:
```
RangeError: index (20) must be in the range [0..20)

STACKTRACE:
#0      List.[] (dart:core-patch/growable_array.dart:136)
#1      FilteredList.[] (package:slickdart/slick_util.dart:78:53)
#2      Node.getPosition (package:slickdart/row_height.dart:110:45)
#3      SlickGrid.scrollRowIntoView (package:slickdart/slick_grid.dart:2687:65)
#4      SlickGrid.handleClick (package:slickdart/slick_grid.dart:2496:16)
#5      _rootRunUnary (dart:async/zone.dart:906)
#6      _ZoneDelegate.runUnary (dart:async/zone.dart:508)
#7      VmTurnZone._onRunUnary.<anonymous closure> (package:angular/core/zone.dart:122:55)
#8      VmTurnZone._onRunBase (package:angular/core/zone.dart:104:16)
#9      VmTurnZone._onRunUnary (package:angular/core/zone.dart:122:7)
#10     _CustomZone.runUnary (dart:async/zone.dart:804)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#12     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:738)
```

This issue is observable on any data's length, I've seen it with 2-3....100 rows.

**Comment by tonosama-atlacatl** [comment]
I think this broke on version 0.1.1+2.
If I set 'multiSelect = true' this is not a problem.
But, while multiSelect is false, I can't click-select the last row unless I actually click on the checkbox.
It's really weird how the last row just seems to fire a different index #.

**Comment by cjkao** [comment]
could you try 0.1.1+3? for index out of bound, i see it happened when using dynamic height with filtered list

**Comment by tonosama-atlacatl** [comment]
yup!, that did it. Thank you!
