### ISSUE TITLE
Grid disappears with the new SDK 1.10.0

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#32]
I'm running:
Dart Editor version 1.10.0.release (STABLE)
Dart SDK version 1.10.0

And there is no grid, no exceptions, it just disappeared...

I tried running some of the examples from the project. I keep getting this: 
Invalid argument (value): Not a valid class token: ""
![screen shot 2015-04-30 at 9 31 27 am](https://cloud.githubusercontent.com/assets/10780925/7417564/cca2a0b8-ef1b-11e4-9c5e-8b8a39a4fa59.png)

**Comment by tonosama-atlacatl** [comment]
I finally got an exception:
Exception: Invalid argument (value): Not a valid class token: "" (package:slickdart/slick_grid.dart:771)
Which is:
div.classes.addAll(clz.split(' '));
is space the separator in this case?

**Comment by cjkao** [comment]
fixed, plz refer 0.1.1+4

**Comment by tonosama-atlacatl** [comment]
You're AWESOME, thank you!
