### ISSUE TITLE
Resetting the dataprovider does NOT reset sorted columns

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#34]
The problem:
While resetting/refreshing the data, if a previous column was clicked and sorted. Upon refreshing the data, the column remains with the last selected sort icon. 

Is there a way to reset a column's sort to say null when the dataprovider is reset/refresh?
or even better, shouldn't all columns reset to non-sorting when the dataprovider is changed?

This issue is pretty much present on all examples w/a reset button, like:
headerRow.html, Formatter.html, etc.

**Comment by tonosama-atlacatl** [comment]
Okay, I guess I missed this... but you can always call:
// _sg == datagrid reference
_sg.setSortColumns([]);

Maybe it was just me, that found it odd that the grid didn't do this by default.

**Comment by tonosama-atlacatl** [comment]
Cjkao, should this be an enhancement/Futures/"will be good" type then?
Just checking :+1:

**Comment by cjkao** [comment]
I think it is bug, since last version is good in my system...gonna fix in next release

**Comment by tonosama-atlacatl** [comment]
thank you :+1:

**Comment by cjkao** [comment]
now reset data by using data=xxx will cancel all selected rows.
but insert/del selected row must manual cancel selected rows

**Comment by tonosama-atlacatl** [comment]
Yup, this works now, thank you!
