### ISSUE TITLE
Grid.height == 100% does not work.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#35]
I'm trying to make my grid's height be 100%, so it resizes with the browser's window.
I see that the viewport is set to a height by:
```dart
// Excerpt from slick_grid.dart ~line 683
// The top viewport does not contain the top panel or header row
   viewportTopH = paneTopH - topPanelH - headerRowH;
```
Unfortunately, If I try setting the height to 100% by using /deep/ etc... once the window is resized, the grid recalculates the height.

I was wondering if this is by design for now, and/or if there is any way to get the 100% height by other means.

Thank you.

**Comment by cjkao** [comment]
shadow dom + customer component has different behavior, need to find out solution

**Comment by cjkao** [comment]
ok, fixed in 0.1.2+2

**Comment by tonosama-atlacatl** [comment]
Awesome!, thank you!

**Comment by tonosama-atlacatl** [comment]
cjkao,

Hi, I was wondering if there is a way to achieve the 100% height without
setting the 100vh viewport on index.html.
Here is the problem with that:
Most users will want to use the datagrid w/some other elements on a layout,
not the datagrid by itself. So, this merits the ability to resize the
height to better accommodate a wide range of screen resolutions. I'm
willing to donate time to get this working, could you steer me on the right
direction, or lend me your advice? is this feasible/crazy/ok?

Thanks,

Alex.
