### ISSUE TITLE
Cannot run 'light-dom-height.html' example, breaks on exception

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#38]
I'm trying to run 'light-dom-height.html' and I get this:
```
Class 'SlickGrid' has no instance getter 'set'.

NoSuchMethodError: method not found: 'set'
Receiver: Instance of 'SlickGrid'
Arguments: []
```
I'm using version: 0.1.3+1

**Comment by cjkao** [comment]
Could you try latest master branch? Just merge develop back to it                                                                                                                                                                                                                                                                                                                                        從我的 BlackBerry 10 智慧型手機傳送。                                                                                                                                                                                                                寄件者： tonosama-atlacatl已傳送： 2015年7月15日星期三 3:59收件者： cjkao/slickdart回覆至： cjkao/slickdart主旨： [slickdart] Cannot run 'light-dom-height.html' example, breaks on exception (#38)I'm trying to run 'light-dom-height.html' and I get this:

Class 'SlickGrid' has no instance getter 'set'.

NoSuchMethodError: method not found: 'set'
Receiver: Instance of 'SlickGrid'
Arguments: []


—Reply to this email directly or view it on GitHub.

**Comment by tonosama-atlacatl** [comment]
No luck man, I'm still getting the same error...
![screen shot 2015-07-15 at 6 03 33 pm](https://cloud.githubusercontent.com/assets/10780925/8713300/efb14320-2b1b-11e5-9b08-88d88fe52eea.png)

**Comment by cjkao** [comment]
do you using  Dart SDK version 1.11.1 ?

**Comment by tonosama-atlacatl** [comment]
Yes, I just ran it on intelliJ as the screencaps show, and It runs, but I get the same exceptions on the browser's console, as the screencaps show.
![screen shot 2015-07-16 at 1 46 17 pm](https://cloud.githubusercontent.com/assets/10780925/8734816/589dcba6-2bc1-11e5-8271-9fc4f3eb987c.png)
![screen shot 2015-07-16 at 1 44 49 pm](https://cloud.githubusercontent.com/assets/10780925/8734822/5e7dcecc-2bc1-11e5-92c9-bf8412983350.png)

**Comment by cjkao** [comment]
grid already rendered, looks like cause from somewhere else, could you debug line 11 to see what happen?

**Comment by tonosama-atlacatl** [comment]
K, I just deleted my local repo and rebased, and no problems. I'm sorry, this is odd, I had done this two days ago and I could still see the exceptions. I'll chalk this one to oddities, sorry about that.
