### ISSUE TITLE
Using Column.fromJSON does NOT work if the JSON came from JSON.encode(Column.toString())

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#40]
Take this formatter as an example:
```
String colStr = new String();
...
superFormatter(int row,int cell,int value,grid.Column columnDef,Map dataRow) {
    colStr = JSON.encode(columnDef.toString());
}

reConstituteCol(){
   Column col = new Column.fromJSON(colStr);
}
```
This yields this exception:
```
Exception: Uncaught Error: type 'String' is not a subtype of type 'Map' of 'm'.
Stack Trace:
#0      Column.Column.fromJSON (package:slickdart/slick_column.dart:176:18)
...
```

**Comment by cjkao** [comment]
it because we try to serialize a formatter [function](http://stackoverflow.com/questions/19916828/dart-is-it-possible-to-de-serialize-a-function-to-from-json).
need new approach to pass functions for serialize/deserialize

**Comment by cjkao** [comment]
I have an idea, maintain a internal editor/formatter pool, when column definition is applied from constructor, it will collect closure or class instance and replace it to new string name, and then, we can made Column to true serializable.

**Comment by cjkao** [comment]
you can do this now,
````dart
    var colStr = JSON.encode(columnDef);
    Column col = new Column.fromJSON(colStr);
````

**Comment by tonosama-atlacatl** [comment]
Yup, that works. Yeah, I see what you mean in regards to the functions not translating into Strings. What you suggest might work, but I'll be a bit concerned w/the keeping track of formatters. As it is right now, we're seeing some slowness w/complex formatters x thousands of rows.

**Comment by cjkao** [comment]
Ah......do not have such use case, may need  a sample case to check bottleneck, but have 3 weeks summer holiday start today , you may need do it by your self...

**Comment by tonosama-atlacatl** [comment]
heheh...😊 No problem...yeah, we're looking into the slowness, but I fear
it's because our use of custom polymer components inside the formatter.
Enjoy your holidays man!
