### ISSUE TITLE
SDK 1.12.0 Broke some stuff.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#42]
I recently upgraded to sdk 1.12.0 and started seeing these errors:
Exception: type 'Text' is not a subtype of type 'StyleElement' in type cast.

Which points to slick_grid.dart, line ~411:
...
stylesheet=((container.parentNode as ShadowRoot).firstChild as StyleElement).sheet;
...

![slickgrid_1 12_error](https://cloud.githubusercontent.com/assets/10780925/9618901/a17083b6-50c7-11e5-81cc-62705e0cdd70.png)

**Comment by cjkao** [comment]
oops..I can not produce this exception after upgrade to 1.12.0, could you upload sample case?

**Comment by tonosama-atlacatl** [comment]
This issue shows up with the new Dartium/Chromium that came with 1.12.0

**Comment by cjkao** [comment]
Upgrade too, as follow, no exception
Dartium: 1.12
Chromium :  39.0.2171.0
line 411

    stylesheet=((container.parentNode as ShadowRoot).firstChild as StyleElement).sheet;

**Comment by tonosama-atlacatl** [comment]
I know, it might be a bit tricky. But, for some reason I had to update my chromium manually. I also had to change where intellij points to, with the latest version from:
https://www.dartlang.org/tools/dartium/

I know this might be really odd, but for some odd reason both browsers are showing the same version (39.0.2171.0). You have to manually upgrade with the one from the link above.

**Comment by tonosama-atlacatl** [comment]
Ok, I think something changed on 1.12, where if I enclose your datagrid inside a Polymer component, it doesn't like it.
I tried to replicate your "simple.html" example as a custom polymer component. This USED to work on the previous SDK version (1.11.3). So, since Polymer hasn't updated their version, we're still on the same 0.16.3+3, which leads me to believe the SDK+Polymer combo is @ fault.

This is what I'm seeing on my Polymer version of your simple example:
![screen shot 2015-09-04 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/10780925/9697007/e0531f46-5331-11e5-83b0-6acafd54d80c.png)

I have a super simple project that illustrates this, but github didn't like my ".zip" file. If you're willing to pursue this further I can email/upload somewhere.

Thank you.

**Comment by cjkao** [comment]
sure, please send it to gmail, thank you

**Comment by tonosama-atlacatl** [comment]
Ok, here you go...
I'm using sdk 1.12.0 and the chromium that came with it on Mac OS X.

**Comment by cjkao** [comment]
never used polymer before, but it ok now, plz refer 0.1.3+4

**Comment by tonosama-atlacatl** [comment]
I'm still seeing that 'method not found: 'children'' error...upgraded to 0.1.3+4
will try sdk 1.12.1 soon...

**Comment by tonosama-atlacatl** [comment]
YEY!!!!, it works w/sdk 1.12.1.....YOU ARE AWESOME!
Thank you...!
