### ISSUE TITLE
exception while running inside a polymer core-overlay "popup"

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#43]
I created a custom polymer component based on the simple example. When I try to run the example inside of a core-overlay popup, the first time it appears ok, but the second time it issues this exception.

![screen shot 2015-09-28 at 2 02 13 pm](https://cloud.githubusercontent.com/assets/10780925/10149720/2a0e43b0-65f0-11e5-9404-46cd84cfa513.png)

My sample project:
https://drive.google.com/file/d/0B8QLD85Y4ynLaW1keW9tZElUY1U/view?usp=sharing

**Comment by cjkao** [comment]
ahh......int parse style error, fixed, plz refer 0.1.3+5

**Comment by tonosama-atlacatl** [comment]
Yup, that did it, thank you!
