### ISSUE TITLE
SDK 1.13 Broke the grid....

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#44]
I'm getting:
 Exception: type 'int' is not a subtype of type 'double' in type >> slick_core.dar:19
![screen shot 2015-11-19 at 2 29 20 pm](https://cloud.githubusercontent.com/assets/10780925/11286525/480cd806-8eca-11e5-953f-36972e3b0649.png)

All examples seemed affected by this...

**Comment by tonosama-atlacatl** [comment]
I fixed it by switching the double to int on slick_core.dart:19, made pull-request #45 
please confirm and let me know if that's not it.

**Comment by cjkao** [comment]
oops....have no use case on this 
thank you, released in 0.1.5+1

**Comment by tonosama-atlacatl** [comment]
Just FYI, SDK 1.13 seems like it broke more stuff...CSSRules, etc.. I'm
still finding stuff :(
