### ISSUE TITLE
Column sorting of booleans doesn't work.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#48]
Looking at the ColumnFilter.dart example. This doesn't work:
```dart
/// web/example/ColumnFilter.dart ~ line 106
if(value1 is bool){
    return value1==true? 1:-1;
}
```
Part of the problem is that booleans don't have a 'compareTo' function. This has been in discussions for quite a while now...
https://groups.google.com/a/dartlang.org/forum/#!msg/misc/5BxhAJJOyow/VrmDv8DtQ1wJ

A "not-so-fancy" solution:
```dart
if(val1.runtimeType == bool){
          result = (val1 == val2 ? 0 : (val1.toString().compareTo(val2.toString()) > 0 ? 1 : -1)) * sign;
}else{
          result = (val1 == val2 ? 0 : (val1.compareTo(val2) > 0 ? 1 : -1)) * sign;
}
```

**Comment by tonosama-atlacatl** [comment]
I think I found a better solution:
```dart
if(val1.runtimeType == bool)return (val1 == val2 ? 0 : (val1 == true?1:-1))*sign;
```

**Comment by cjkao** [comment]
ok, add in 749d060d5b3d49e81ace9b762a9f52e019590f76

**Comment by tonosama-atlacatl** [comment]
Also, this breaks if the column type is DateTime and some rows are null.
