### ISSUE TITLE
Resetting selected rows does not clear the cell's "active" class

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#49]
I hope this is an option I overlooked on my part, but we're finding hard to re-select the same row by clicking on the same cell, after calling:
```dart
dg.setSelectedRows([]);
```
**The problem:**
The call above does not clear the "active" css class added when the cell was clicked.

perhaps there is a way to not use the "active", or simply force a clear similar to what happens when one clicks on a different row.

**Comment by cjkao** [comment]
use `resetActiveCell();` to enable click event

**Comment by tonosama-atlacatl** [comment]
Yup, that did it, Thank you!
