### ISSUE TITLE
Hide column headers

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#50]
Is there a way to hide the columns' headers? 
I tried looking for an option, but the closest I found where 'showHeaderRow' and 'showTopPanel', but neither one is related to the column header row.

If there isn't, could you point me to where I should look to get this working?

Thank you,

Alex

**Comment by cjkao** [comment]
you can override style, for this example, there will be only 2px header  , the default style in slick.grid.css
````
.slick-header-column.ui-state-default {
  height: 1px;
  padding: 1px;
}
````

**Comment by tonosama-atlacatl** [comment]
Thank you, yup, I fixed it by targeting the div this way:
```
#grid /deep/ div.slick-header-columns {
        display: none;
      }
```

I was wondering, I have a similar method to hid the scrollbars from the viewport. Is there an option somewhere to force the absence of scrollbars?

**Comment by cjkao** [comment]
I think you can use `resizeCanvas()` to rebuild viewport

**Comment by tonosama-atlacatl** [comment]
Right, but the problem is that when someone resizes the window, this gets called anyways.
So, the viewport is always "width: 100%", but it's child div ".grid-canvas" is some specific width...
I guess what I'm looking for is to fool the canvas into thinking its width is "100%" and not display a scrollbar...

I know, this might sound crazy, but in our implementation, we want to never display a scrollbar, even if there are more rows/columns that the canvas can show...

I've managed to get this working by:
``` css
    #grid /deep/ div.slick-viewport[style*="overflow: auto;"] {
        overflow: hidden !important;
      }
```
This will remove the scrollbars, but the canvas will always be shorter due to it still thinking it needs space for a scroll....

**Comment by cjkao** [comment]
Yes, this is sound crazy and interesting use case. 
BTW, use `/deep/` is depreciated, you may need to refactor it in the future
