### ISSUE TITLE
Column resize doesn't work under FireFox

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#51]
Column resizing by click+drag does not work at all in FireFox.
Tested with:
Firefox 44.0.2
OS X El Capitan 10.11.3

**Comment by cjkao** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1244533, need a workaround

**Comment by cjkao** [comment]
fixed in 0.1.5+4

**Comment by tonosama-atlacatl** [comment]
Yup, I can confirm this works on Firefox.
