### ISSUE TITLE
SDK 1.15 broken on polymer 1.0 RC15

### ISSUE THREAD

**Issue by cjkao** [cjkao/slickdart#53]

**Comment by tonosama-atlacatl** [comment]
What errors are you seeing? and is this broken with polymer 1 or < 1?
We're currently testing SDK 1.15 and polymer: ^0.16.0 and so far, only see some oddities while running in FireFox.

**Comment by cjkao** [comment]
Polymer 1.0
After verified, not this category, it broken in autonotify_observe and reflectable

**Comment by cjkao** [comment]
NoSuchMethodError: method not found: 'previousNode' on  package:slickdart/slick_grid.dart:2455:35 @  polymer version: "1.0.0-rc.15"

**Comment by cjkao** [comment]
the sequence of dart import affect how script generation on to html page
when customize element(non polymer) is referenced, it must import first in dart script

**Comment by cjkao** [comment]
fixed in polymer 1.0rc16
