### ISSUE TITLE
Selecting one row only sets the row's clicked cell to "active" but not the rest of the cells.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [cjkao/slickdart#54]
Issue:
When selecting a row, if I click on cell "A", the row is highlighted and the row selection event is dispatched. Clicking back on cell "A" will do nothing and it would not dispatch the row selection event since it is now set to "active", but the rest of the other cells are not set to "active". So, If I click on cell "B", despite the row being _already_ selected, I will get another row selection event.

Please let me know if I'm missing a setting or option to enable proper row selection. 

My expectation would be that if I click on any row's cell, I select the row, subsequent clicks on that row, on any cell should not fire a row selection since it's already selected. Deselecting the row should put it back to an inactive state and able to be reselected by clicking on any cell on that same row.

**Comment by cjkao** [comment]
I think you can use `RowSelectionModel({'selectActiveRow':false})` to disable event

**Comment by tonosama-atlacatl** [comment]
Yup, that works, thank you!
